name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main  # Trigger only when pushing to the 'main' branch

jobs:
  build-and-push:
    name: Build and Push to ACR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Log in to ACR
      uses: docker/login-action@v3
      with:
        registry: englamp-fsfgfxegcmbratc7.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build Docker image for Apache
      run: |
        docker build -t englamp.azurecr.io/englamp_apache:latest .

    - name: Push Docker image to ACR
      run: |
        docker push englamp.azurecr.io/englamp_apache:latest